sudo: false
language: ruby

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

matrix:
  include:
    - rvm: 2.5.1
    - rvm: 2.4.4
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

bundler_args: --without docs development

script: bundle exec rake
